In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
zero = np.zeros((2,2))

In [7]:
print(zero)

[[0. 0.]
 [0. 0.]]


In [8]:
zero

array([[0., 0.],
       [0., 0.]])

In [20]:
full=np.full((2,4),5)

In [21]:
full

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [26]:
# creating an identity matrix
idem=np.eye(4)

In [27]:
idem

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# Dimensional arrays
zerod=np.array(1)
zerod

array(1)

In [30]:
oned=np.array([1,1])
oned

array([1, 1])

In [34]:
x=[[1,2,3],
   [4,5,6]]
twod=np.array(x)

twod

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
twod.shape

(2, 3)

In [41]:
x=[[[1,2,3],[1,2,3]],
[[4,5,6],[4,5,6]]]
threed=np.array(x)
threed

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]])

In [42]:
threed.shape

(2, 2, 3)

In [47]:
multid = np.array([1,2,3],ndmin=5)
multid

array([[[[[1, 2, 3]]]]])

In [53]:
# reading array values
arr= np.array([range(0,11)])
for i in range(len(arr)):
    print(arr[i],end=" ")

[ 0  1  2  3  4  5  6  7  8  9 10] 

In [98]:
# update the index value
arr= np.array([[range(0,11)],[range(11,22)]],dtype=int)
print(arr)
# arr


[[[ 0  1  2  3  4  5  6  7  8  9 10]]

 [[11 12 13 14 15 16 17 18 19 20 21]]]


In [99]:
arr.shape

(2, 1, 11)

In [100]:
arr[0]=1

In [101]:
print(arr)

[[[ 1  1  1  1  1  1  1  1  1  1  1]]

 [[11 12 13 14 15 16 17 18 19 20 21]]]


In [113]:
arr=np.delete(arr,0)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [115]:
res=np.where(arr==11)
res

(array([0], dtype=int64),)

In [118]:
x=np.sort(arr,reverse=True) # reverse = True is not valid in the numpy sort method
x

TypeError: _sort_dispatcher() got an unexpected keyword argument 'reverse'

In [119]:
a=np.array([1,2,3],dtype=np.int64)

In [120]:
b=np.array([4,5,6],dtype=np.int64)

In [121]:
addition = np.add(a,b)
addition

array([5, 7, 9], dtype=int64)

In [124]:
subst = np.subtract(a,b)
subst

array([-3, -3, -3], dtype=int64)

In [123]:
mul = np.multiply(a,b)
mul

array([ 4, 10, 18], dtype=int64)

In [125]:
div = np.divide(a,b)
div

array([0.25, 0.4 , 0.5 ])

In [126]:
sq = np.sqrt(a)
sq

array([1.        , 1.41421356, 1.73205081])

In [127]:
x = np.array([[1,2,3],[1,2,3],[1,2,3]])
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [128]:
x.shape

(3, 3)

In [130]:
trans = np.transpose(x)
trans

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])